theme: jekyll-theme-architect
title: Brian D. Caravantes Hernandez 
description: Hard worker, works well with a team or self-directed, good problem solving and analytic skills, disciplined, fast learner,fluent in Spanish speaking and writing.
