theme: jekyll-theme-architect
title: Brian D. Caravantes Hernandez 
description: Software Developer
repository: carav008/carav008.github.io 
footer-links:
  email: carav008@morris.umn.edu
  github: carav008
  linkedin: brian-caravantes-793378b8
 


exclude: 
  - Gemfile
  - Gemfile.lock
