theme: jekyll-theme-architect
title: Brian D. Caravantes Hernandez 
description: Systems Engineer 
repository: carav008/carav008.github.io 
footer-links:
  email: briancaravantes1@gmail.com 
  github: carav008
  linkedin: brian-caravantes-793378b8
 


exclude: 
  - Gemfile
  - Gemfile.lock
